### ISSUE TITLE
Twitch Hide Viewer Bots

### ISSUE THREAD

**Issue by FloraleiBloodwood** [ismailkarsli/userscripts#1]
Hey, I wondered if it would be possible for you to make a variation of your bot hider which will instead highlight the bots with red color? There was an addon that did this but it stopped working some time ago. :(

**Comment by ismailkarsli** [comment]
Here you go: https://github.com/ismailkarsli/userscripts/raw/main/twitch-highlight-viewer-bots.user.js

**Comment by FloraleiBloodwood** [comment]
Thanks for the quick help, Ismail, however it doesn't seem to work. I know
it's running, but it does not highlight bots (not streaming at the moment,
but it should highlight for instance Streamlabs, which is on the
twitchinsights.net bot list).

**Comment by ismailkarsli** [comment]
This tool only hides/highlights bots in the **viewer list** and not chat itself. If you want to highlight chat messages by bots, then use this: https://github.com/ismailkarsli/userscripts/raw/main/twitch-highlight-bots.user.js

I edited the old script for chat.
